TEXT_TO_SPEECH_CHUNK_SIZE_SECONDS = 1
PER_CHUNK_ALLOWANCE_SECONDS = 0.01
ALLOWED_IDLE_TIME = 15
CHECK_IN_IDLE_TIME = 5
AGENT_RECORDING_SUFFIX = "agent"
HUMAN_RECORDING_SUFFIX = "human"
ALL_RECORDING_SUFFIX = "all"